"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision}
Create Date: ${create_date}

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql # Importe postgresql pour les types spécifiques comme UUID, JSONB

# Importe les modèles de notre application pour les références de type si nécessaire
# from ..models import User, Project, ...

# revision identifiers, used by Alembic.
revision = ${up_revision}
down_revision = ${down_revision}
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
${upgrade_ops}
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
${downgrade_ops}
    # ### end Alembic commands ###

