# Fichier placeholder pour deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qc-service-deployment # Nom du déploiement Kubernetes
  labels:
    app: qc-service # Labels pour identifier le déploiement
spec:
  replicas: 2 # Nombre d'instances (pods) du QC Service à maintenir en cours d'exécution
  selector:
    matchLabels:
      app: qc-service # Sélecteur pour les pods gérés par ce déploiement
  template:
    metadata:
      labels:
        app: qc-service # Labels pour les pods
    spec:
      containers:
      - name: qc-service # Nom du conteneur
        image: your-docker-registry.com/math-agent/qc-service:latest # Remplacez par l'image Docker de votre QC Service
        ports:
        - containerPort: 8000 # Le port sur lequel l'application FastAPI écoute
        resources:
          requests: # Ressources minimales requises par le conteneur
            cpu: "400m" # 400 milliCPU
            memory: "1024Mi" # 1024 Mégaoctets (1 Go)
          limits: # Limites maximales de ressources que le conteneur peut utiliser
            cpu: "2000m" # 2000 milliCPU (2 CPU complets)
            memory: "4096Mi" # 4096 Mégaoctets (4 Go)
        livenessProbe: # Sonde de vivacité: vérifie si l'application est toujours en cours d'exécution
          httpGet:
            path: /health # Endpoint de santé du QC Service
            port: 8000
          initialDelaySeconds: 25 # Délai avant la première vérification
          periodSeconds: 10 # Fréquence des vérifications
        readinessProbe: # Sonde de préparation: vérifie si l'application est prête à recevoir du trafic
          httpGet:
            path: /ready # Endpoint de préparation du QC Service
            port: 8000
          initialDelaySeconds: 30 # Délai avant la première vérification
          periodSeconds: 10 # Fréquence des vérifications
        env: # Variables d'environnement pour le conteneur
        - name: KB_SERVICE_URL # URL du service de base de connaissances
          value: http://kb-service-service:80 # Communication interne via le nom du service Kubernetes
        # Ajoutez d'autres variables d'environnement nécessaires ici pour les outils externes (ex: Z3_PATH, WOLFRAM_ALPHA_API_KEY)
